name: Build and upload agroforestry

on:
  push:
    tags:
      - v*

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install
      - run: npm run build
      - run: zip -j dist.zip dist/*
      - run: curl -F 'dist=@dist.zip' https://agroforestry.ugent.be/upload.php?key=${{ secrets.UPLOAD_KEY }}
